# Generated by Django 4.1.7 on 2023-05-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psix_test", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Answer",
            new_name="PSTAnswer",
        ),
        migrations.RenameModel(
            old_name="Question",
            new_name="PSTQuestion",
        ),
    ]
