# Generated by Django 4.1.7 on 2023-05-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psix_test", "0002_rename_answer_pstanswer_rename_question_pstquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pstanswer",
            name="job",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="kasb"
            ),
        ),
    ]
