# Generated by Django 4.1.7 on 2023-05-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psix_test", "0003_pstanswer_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pstanswer",
            name="job",
        ),
    ]
