# Generated by Django 4.1.7 on 2023-03-31 06:15

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Katta kategoriya"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name="Kategoriya haqida",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("deactive", "Faol emas"),
                            ("delate", "O'chirish"),
                        ],
                        default="active",
                        max_length=100,
                        verbose_name="Holati",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Katta kategoriya",
                "verbose_name_plural": "Katta kategoriyalar",
                "ordering": ("-created_at", "status"),
            },
        ),
        migrations.CreateModel(
            name="Sub_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Kategoriya nomi"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name="Kategoriya haqida",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("oddiy", "Oddiy test"),
                            ("ota", "O'quvchi tepmeramentini aniqlash"),
                            ("ktta", "KASB TANLASHGA TAYYORLIKNI ANIQLASH"),
                            ("ehsa", "Emotsional holati va stressni aniqlash"),
                            ("kta", "Kasb tiplarini aniqlash"),
                        ],
                        default="oddiy",
                        max_length=100,
                        verbose_name="Test turi",
                    ),
                ),
                (
                    "number_of_questions",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Savollar soni"
                    ),
                ),
                (
                    "time_duration",
                    models.CharField(
                        blank=True,
                        default=0,
                        max_length=3,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{1,3}$")
                        ],
                        verbose_name="Test davomiyligi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("deactive", "Faol emas"),
                            ("delate", "O'chirish"),
                        ],
                        default="active",
                        max_length=100,
                        verbose_name="Holati",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="test_app.category",
                        verbose_name="Katta kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ("-created_at", "status"),
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=350, verbose_name="Savol matni"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="question", unique=True
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="question_photo/%Y/%m/%d/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("no", "Yo'q"),
                            ("tabiat", "Tabiat"),
                            ("texnika", "texnika"),
                            ("belgi", "Belgi"),
                            ("sanat", "San'at"),
                            ("inson", "Inson"),
                        ],
                        default="no",
                        max_length=100,
                        verbose_name="Kasb turi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("deactive", "Faol emas"),
                            ("delate", "O'chirish"),
                        ],
                        default="active",
                        max_length=100,
                        verbose_name="Holati",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question",
                        to="test_app.sub_category",
                        verbose_name="Kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
                "ordering": ("-created_at", "status"),
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True, max_length=350, null=True, verbose_name="Variant"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="answer", unique=True
                    ),
                ),
                (
                    "ball",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Variant ostidagi Ball",
                    ),
                ),
                (
                    "true_answer",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="To'g'ri javob",
                    ),
                ),
                (
                    "question_result",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name="Savol natijasi",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="answer_photo/%Y/%m/%d/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol"),
                            ("deactive", "Faol emas"),
                            ("delate", "O'chirish"),
                        ],
                        default="active",
                        max_length=100,
                        verbose_name="Holati",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="test_app.question",
                        verbose_name="Savol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Javob",
                "verbose_name_plural": "Javoblar",
                "ordering": ("-created_at", "status"),
            },
        ),
    ]
