# Generated by Django 4.1.7 on 2023-02-18 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question",
                to="test_app.sub_category",
                verbose_name="Kategoriya",
            ),
        ),
        migrations.AlterField(
            model_name="sub_category",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Kategoriya nomi"
            ),
        ),
    ]
