# Generated by Django 4.1.7 on 2023-03-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "Yo'q"),
                    ("tabiat", "Tabiat"),
                    ("texnika", "texnika"),
                    ("belgi", "Belgi"),
                    ("sanat", "San'at"),
                    ("inson", "Inson"),
                ],
                default="no",
                max_length=100,
                null=True,
                verbose_name="Kasb turi",
            ),
        ),
    ]
