# Generated by Django 4.1.7 on 2023-05-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_alter_answer_created_at_alter_answer_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ("created_at", "status"),
                "verbose_name": "Javob",
                "verbose_name_plural": "Javoblar",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("created_at", "status"),
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
            },
        ),
    ]
