# Generated by Django 4.1.7 on 2023-05-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_sub_category_lesson_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("created_at", "status"),
                "verbose_name": "Katta kategoriya",
                "verbose_name_plural": "Katta kategoriyalar",
            },
        ),
        migrations.AlterModelOptions(
            name="sub_category",
            options={
                "ordering": ("created_at", "status"),
                "verbose_name": "kichik kategoriya",
                "verbose_name_plural": "kichik kategoriyalar",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="status",
            field=models.CharField(
                choices=[("active", "Faol"), ("deactive", "Faol emas")],
                default="active",
                max_length=100,
                verbose_name="Holati",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("active", "Faol"), ("deactive", "Faol emas")],
                default="active",
                max_length=100,
                verbose_name="Holati",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(
                blank=True, max_length=350, null=True, verbose_name="Savol matni"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[("active", "Faol"), ("deactive", "Faol emas")],
                default="active",
                max_length=100,
                verbose_name="Holati",
            ),
        ),
        migrations.AlterField(
            model_name="sub_category",
            name="status",
            field=models.CharField(
                choices=[("active", "Faol"), ("deactive", "Faol emas")],
                default="active",
                max_length=100,
                verbose_name="Holati",
            ),
        ),
    ]
