# Generated by Django 4.1.7 on 2023-04-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_alter_question_job_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sub_category",
            options={
                "ordering": ("-created_at", "status"),
                "verbose_name": "kichik kategoriya",
                "verbose_name_plural": "kichik kategoriyalar",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="question_result",
            field=models.TextField(
                blank=True, null=True, verbose_name="Javob natijasi"
            ),
        ),
    ]
