# Generated by Django 4.1.7 on 2023-05-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_alter_answer_options_alter_question_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="job",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tabiat", "Tabiat"),
                    ("texnika", "texnika"),
                    ("belgi", "Belgi"),
                    ("sanat", "San'at"),
                    ("inson", "Inson"),
                ],
                default="tabiat",
                max_length=30,
                null=True,
                verbose_name="Kasb",
            ),
        ),
    ]
