# Generated by Django 4.1.7 on 2023-05-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_alter_category_options_alter_sub_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sub_category",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Kategoriya nomi"),
        ),
    ]
