# Generated by Django 4.1.7 on 2023-04-03 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_alter_sub_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sub_category",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="test_app.category",
                verbose_name="Katta kategoriya",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sub_category",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("oddiy", "Oddiy test"),
                    ("ota", "O'quvchi tepmeramentini aniqlash"),
                    ("ktta", "Kasb tanlashga tayorgarlikni aniqlash"),
                    ("ehsa", "Emotsional holati va stressni aniqlash"),
                    ("kta", "Kasb tiplarini aniqlash"),
                ],
                default="oddiy",
                max_length=100,
                verbose_name="Test turi",
            ),
        ),
    ]
