# Generated by Django 4.1.7 on 2023-04-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0004_alter_sub_category_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "No'malum"),
                    ("tabiat", "Tabiat"),
                    ("texnika", "Texnika"),
                    ("belgi", "Belgi"),
                    ("sanat", "San'at"),
                    ("inson", "Inson"),
                ],
                default="no",
                max_length=100,
                null=True,
                verbose_name="Kasb turi",
            ),
        ),
        migrations.AlterField(
            model_name="sub_category",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("ota", "O'quvchi tepmeramentini aniqlash"),
                    ("ktta", "Kasb tanlashga tayorgarlikni aniqlash"),
                    ("ehsa", "Emotsional holati va stressni aniqlash"),
                    ("kta", "Kasb tiplarini aniqlash"),
                ],
                default="oddiy",
                max_length=100,
                verbose_name="Test turi",
            ),
        ),
    ]
