# Generated by Django 4.1.7 on 2023-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="student",
            managers=[],
        ),
        migrations.RenameField(
            model_name="student",
            old_name="sex",
            new_name="gender",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="student",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_photo", verbose_name="rasm"
            ),
        ),
    ]
