# Generated by Django 4.1.7 on 2023-05-25 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("psix_test", "0001_initial"),
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PSTResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ball", models.PositiveIntegerField(default=0, verbose_name="ball")),
                (
                    "tashxis",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="tashxis"
                    ),
                ),
                ("test_api", models.JSONField(blank=True, default={}, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pstresult_subcategory",
                        to="psix_test.pstsub_category",
                        verbose_name="kichik kategoriya",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psttest_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "PSTTest natijasi",
                "verbose_name_plural": "PSTTest natijalari",
                "ordering": ("-created_at",),
            },
        ),
    ]
