# Generated by Django 4.1.7 on 2023-03-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_alter_student_managers_rename_sex_student_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="C:/Users/xatam/OneDrive/Pictures/Saved Pictures/default_person_picture (2).png",
                null=True,
                upload_to="user_photo",
                verbose_name="rasm",
            ),
        ),
    ]
