# Generated by Django 4.1.7 on 2023-03-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_alter_student_student_tests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="father_password",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="ota-ona paroli"
            ),
        ),
    ]
