# Generated by Django 4.1.7 on 2023-04-17 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_alter_result_ball"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                default=1, max_length=254, unique=True, verbose_name="email"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="father_email",
            field=models.EmailField(
                default=1, max_length=254, unique=True, verbose_name="email"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="father_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon raqamingiz 9 bilan boshlanishi va 12 belgidan oshmasligi lozim. Masalan: 998334568978",
                        regex="^[\\+]?[9]{2}[8]?[0-9]{2}?[0-9]{3}?[0-9]{2}?[0-9]{2}$",
                    )
                ],
                verbose_name="ota-ona raqami",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("man", "Man"), ("woman", "Woman")],
                max_length=50,
                verbose_name="jins",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon raqamingiz 9 bilan boshlanishi va 12 belgidan oshmasligi lozim. Masalan: 998334568978",
                        regex="^[\\+]?[9]{2}[8]?[0-9]{2}?[0-9]{3}?[0-9]{2}?[0-9]{2}$",
                    )
                ],
                verbose_name="shaxsiy raqam",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default_person_picture.png",
                null=True,
                upload_to="user_photo",
                verbose_name="rasm",
            ),
        ),
    ]
