# Generated by Django 4.1.7 on 2023-05-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_remove_pstresult_tashxis_pstresult_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pstresult",
            name="ball",
        ),
    ]
