# Generated by Django 4.1.7 on 2023-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_alter_student_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="C:/Users/xatam/OneDrive/Pictures/Saved_Pictures/default_person_picture(2).png",
                null=True,
                upload_to="user_photo",
                verbose_name="rasm",
            ),
        ),
    ]
