# Generated by Django 4.1.7 on 2023-05-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_result_try_count_alter_result_ball"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("active", "Faol"), ("deactive", "Faol emas")],
                default="active",
                max_length=30,
                verbose_name="holati",
            ),
        ),
    ]
