# Generated by Django 4.1.7 on 2023-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_remove_pstresult_ball"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="permission_to_test",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
