# Generated by Django 4.1.7 on 2023-03-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_delete_result"),
        ("user_app", "0004_alter_student_father_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_tests",
        ),
        migrations.AddField(
            model_name="student",
            name="student_tests",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_tests",
                to="test_app.sub_category",
            ),
            preserve_default=False,
        ),
    ]
