# Generated by Django 4.1.7 on 2023-03-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_delete_result"),
        ("user_app", "0005_remove_student_student_tests_student_student_tests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_tests",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_tests",
                to="test_app.sub_category",
            ),
        ),
    ]
