# Generated by Django 4.1.7 on 2023-03-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0006_alter_student_student_tests"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="father_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
    ]
